name: bake

on:
  push:
    tags:
      - v*

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Extract tag name
        run: echo "DOCKER_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          set: |
            *.tags=wallarm/sysbindings:${{ env.DOCKER_TAG }}
